version: "2"

run:
  timeout: 30m
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - goimports

linters:
  disable-all: true
  enable:
    # Error handling
    - errcheck
    - errorlint
    - nilerr
    - nilnil

    # Code quality
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Style
    - godot
    - revive

    # Security
    - gosec

    # Bugs
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    - contextcheck
    - durationcheck
    - misspell
    - nakedret
    - noctx
    - predeclared
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign

    # Complexity (enabled but configured)
    - cyclop
    - funlen
    - gocognit

    # Format
    - asciicheck
    - gomoddirectives
    - promlinter
    - tagliatelle

    # Documentation
    - nolintlint

formatters-settings:
  goimports:
    local-prefixes: go.pixelfactory.io/pkg/observability/log

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeExprCopy
      - rangeValCopy

  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  govet:
    disable:
      - fieldalignment

  nakedret:
    max-func-lines: 1

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab

  cyclop:
    max-complexity: 30
    package-average: 10.0

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

  godot:
    scope: all
    period: true

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-rules:
    # Exclude certain linters from running on test files
    - path: _test\.go
      linters:
        - bodyclose
        - dupl
        - errcheck
        - funlen
        - goconst
        - gosec
        - noctx
        - wrapcheck
